module.exports = {
  "extends": [
    "eslint:recommended",
    "plugin:node/recommended",
    "plugin:ava/recommended",
    "plugin:unicorn/recommended",
    "plugin:lodash/canonical"
  ],
  "plugins": [
    "node",
    "promise",
    "ava",
    "no-loops",
    "unicorn",
    "lodash",
    "destructuring"
  ],
  "env": {
    "es6": true,
    "browser": false,
    "node": true,
    "mongo": true
  },
  "parserOptions": {
    "ecmaVersion": 2017,
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true,
      "arrowFunctions": true,
      "blockBindings": true,
      "classes": true,
      "defaultParameters": true,
      "destructuring": true,
      "forOf": true,
      "generators": true,
      "modules": true,
      "objectLiteralComputedProperties": true,
      "objectLiteralDuplicateProperties": true,
      "objectLiteralShorthandMethods": true,
      "objectLiteralShorthandProperties": true,
      "regexUFlag": true,
      "regexYFlag": true,
      "restParams": true,
      "spread": true,
      "superInFunctions": true,
      "templateStrings": true,
      "unicodeCodePointEscapes": true
    }
  },
  "rules": {
    "no-loops/no-loops": 1,

    "node/exports-style": ["error", "module.exports"],

    "promise/always-return": 1,
    "promise/no-return-wrap": 2,
    "promise/param-names": 2,
    "promise/catch-or-return": 1,
    "promise/no-native": 0,
    "promise/no-nesting": 1,
    "promise/no-promise-in-callback": 1,
    "promise/no-callback-in-promise": 1,
    "promise/avoid-new": 0,
    "promise/no-return-in-finally": 2,
    "promise/prefer-await-to-then": 1,
    "promise/prefer-await-to-callbacks": 1,
    
    "lodash/prefer-get": 1,
    "lodash/prefer-includes": 1,
    "lodash/prefer-is-nil": 1,
    "lodash/prefer-times": 1,
    "lodash/prefer-map": 2,
    "lodash/prefer-filter": 2,

    "unicorn/catch-error-name": ["error", { "name": "err" }],
    "unicorn/explicit-length-check": 0,
    "unicorn/filename-case": ["warn", { "case": "kebabCase" }],
    "unicorn/no-abusive-eslint-disable": 2,
    "unicorn/throw-new-error": 2,
    "unicorn/number-literal-case": 2,
    "unicorn/escape-case": 2,
    "unicorn/no-array-instanceof": 2,
    "unicorn/no-new-buffer": 2,
    "unicorn/no-hex-escape": 2,
    "unicorn/custom-error-definition": 2,
    "unicorn/prefer-starts-ends-with": 2,
    "unicorn/prefer-type-error": 2,
    "unicorn/no-process-exit": 0,
    "unicorn/no-fn-reference-in-iterator": 0,
    "unicorn/import-index": 2,
    "unicorn/regex-shorthand": 2,

    "destructuring/in-params": ["warn", { "max-params" : 0 }],
    
    "arrow-spacing": ["warn", {"before": true, "after": true}],
    "block-spacing": ["warn", "always"],
    "comma-dangle": ["error", "never"],
    "comma-spacing": ["warn", { "before": false, "after": true }],
    "computed-property-spacing": ["warn", "never"],
    "dot-notation": ["warn", { "allowPattern": "^[a-z]+(_[a-z]+)+$" }],
    "eol-last": ["warn", "never"],
    "eqeqeq": ["warn", "smart"],
    "func-names": ["warn", "as-needed"],
    "func-style": ["warn", "declaration", { "allowArrowFunctions": true }],
    "indent": ["warn", 2, { "SwitchCase": "warn" }],
    "max-len": ["warn", { "code": 120 }],
    "no-array-constructor": 1,
    "no-bitwise": 1,
    "no-console": 0,
    "no-const-assign": 2,
    "no-continue": 0,
    "no-duplicate-imports": 1,
    "no-eval": 2,
    "no-extra-bind": 1,
    "no-irregular-whitespace": 1,
    "no-lonely-if": 1,
    "no-loop-func": 1,
    "no-mixed-requires": 1,
    "no-new-require": 1,
    "no-param-reassign": 1,
    "no-process-exit": 0,
    "no-return-await": 1,
    "no-throw-literal": 1,
    "no-trailing-spaces": 1,
    "no-undef-init": 1,
    "no-underscore-dangle": 1,
    "no-unneeded-ternary": 1,
    "no-use-before-define": ["warn", "nofunc"],
    "no-useless-concat": 1,
    "no-var": 2,
    "object-curly-spacing": ["warn", "always"],
    "object-shorthand": ["warn", "always"],
    "prefer-const": 1,
    "prefer-template": 1,
    "quotes": ["warn", "single", { "allowTemplateLiterals": true }],
    "require-await": 1,
    "semi": ["warn", "always"],
    "space-before-blocks": ["warn", "always"],
    "space-before-function-paren": ["warn", "always"],
    "space-infix-ops": "warn"
  }
};
